version: '3.3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - todolistify-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "80"
    networks:
      - todolistify-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
    ## APP
    - TODOLISTIFY_PORT=${TODOLISTIFY_PORT:-3000}
    # App
    - YEMENCAREERS_APP_PROT=${TODOLISTIFY_PORT:-3000}
    - YEMENCAREERS_APP_FRONTEND_URL=${YEMENCAREERS_APP_FRONTEND_URL:-"http://localhost:80"}
    - NODE_ENV=production
    # JWT
    - YEMENCAREERS_JWT_SECREAT=${YEMENCAREERS_JWT_SECREAT:-"password123"}
    - YEMENCAREERS_JWT_EXPIRESIN=${YEMENCAREERS_JWT_EXPIRESIN:-"3h"}
    - YEMENCAREERS_JWT_LONG_EXPIRESIN=${YEMENCAREERS_JWT_LONG_EXPIRESIN:-"3d"}
    # Database
    - YEMENCAREERS_DATABASE_HOST=${YEMENCAREERS_DATABASE_HOST:-"localhost"}
    - YEMENCAREERS_DATABASE_PORT=${YEMENCAREERS_DATABASE_PORT:-5432}
    - YEMENCAREERS_DATABASE_USERNAME=${YEMENCAREERS_DATABASE_USERNAME:-"postgres"}
    - YEMENCAREERS_DATABASE_PASSWORD=${YEMENCAREERS_DATABASE_PASSWORD:-"postgres"}
    - YEMENCAREERS_DATABASE_NAME=${YEMENCAREERS_DATABASE_NAME:-"yemencareers"}
    - YEMENCAREERS_DATABASE_SYNC=${YEMENCAREERS_DATABASE_SYNC:-"true"}
    # Password
    - YEMENCAREERS_PASSWORD_SALT_RANGE=${YEMENCAREERS_PASSWORD_SALT_RANGE:-12}
    depends_on:
      - postgres
    networks:
      - todolistify-network

  postgres:
    image: postgres:16-alpine
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${YEMENCAREERS_DATABASE_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${YEMENCAREERS_DATABASE_PASSWORD:-postgres}
      - POSTGRES_DB=${YEMENCAREERS_DATABASE_NAME:-yemencareers}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todolistify-network

networks:
  todolistify-network:
    driver: bridge

volumes:
  postgres_data: 